HalloweenController v0.0.1/Models/Button.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HalloweenController_v0._0._1.Models{
    
    public enum ResponseList
    {
     [Description("This option will disable all buttons for the amount of time specified in the timeout")]
     lockall,
     [Description("This option will disable the clicked button for the amount of time specified in the timeout")]
     lockbutton,
     [Description("This option will not disable any buttons")]
     locknone,
     [Description("This option will not disable any buttons and will display the web service response")]
     actual,


    }

    public class Button
    {
        [Key]
        public int ButtonID { get; set; }
        public string Label { get; set; }
        public string Style { get; set; }
        public string URI { get; set; }
        public string Response { get; set; }
        public int TimeOut { get; set; }
        public string Users { get; set; }

    }
}

HalloweenController v0.0.1/Controllers/ButtonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HalloweenController_v0._0._1.Models;
using HalloweenController_v0._0._1.DAL;
using System.ComponentModel;

namespace HalloweenController_v0._0._1.Controllers
{
    public class ButtonsController : Controller
    {
        private PanelContext db = new PanelContext();


        public bool RunMessage = false;

        // GET: Buttons
        public ActionResult Index()
        {


            //SelectList ResponseTypes = new SelectList(RList);
            //ViewData["ResponseTypes"] = ResponseTypes;

            return View(db.Buttons.ToList());
        }

      public ActionResult TestClick(string URI)

        {
            bool PostSuccess = false;
            var curUser = User.Identity.Name.ToString();
            MyMethods.WriteToLog(curUser + " has pressed the button... " + URI);
            try
            {
                PostSuccess = REST.POST(URI, "", "text/plain");
            }
            catch (Exception e)
            {
                MyMethods.WriteToLog(e.ToString());
                //throw;
            }
            
            //return View();
            if (PostSuccess)
            {
                MyMethods.ShowDisplay = true;
            
              return Redirect(Request.UrlReferrer.ToString());
                //return Content("<script language='javascript' type='text/javascript'>alert('Hello world!');</script>"); 
            }
            else
            {
                MyMethods.ShowDisplay = false;
              return RedirectToAction("ErrorPanel");  
            }

            
            //return JavaScript("<script>hideDiv(\"ButtonSuccess\")</script>");
        }

        public ActionResult Panel()
        {
            ViewData["DisplayMessage"] = MyMethods.ShowDisplay;
            var curUser = User.Identity.Name.ToString();
            //System.IO.StreamWriter file = new System.IO.StreamWriter(@"C:\Temp\ControllerLog.txt");
            //file.WriteLine(curUser + " has accessed their panel... " + DateTime.Now.ToString());
            //file.Close();
            //MyMethods.WriteToLog(curUser + " has accessed their panel... ");

            var ButtonList = db.Buttons.ToList();
            bool UserCanUseButton = false;
            //run through each button, remove buttons whos list of users does not match current user
            try
            {
                var ButtonCount = ButtonList.Count();
                for (int  i= 0; i <= (ButtonCount - 1); i++)
                {
                    var But = ButtonList[i];

                    //Grab a list of users allowed to use this button
                    var userList = But.Users;

                    UserCanUseButton = false;
                    if (userList == null)
                    {
                       
                    }
                    else
                    {
                        string[] aUsers = userList.Split(',');

                   

                        foreach (var ForUser in aUsers)
                        {
                            if (ForUser == curUser )
                            {
                                UserCanUseButton = true;
                            }
                        }
                    }

                    if (curUser == "admin@gmail.com" | curUser == "administrator@gmail.com")
                    {
                        UserCanUseButton = true;
                    }

                    if (UserCanUseButton == false)
                    {
                        ButtonList.Remove(But);
                        i = i - 1;
                        ButtonCount = ButtonCount - 1;
                    }


                }
            }
            catch (Exception e)
            {
                MyMethods.WriteToLog(e.ToString());
                //throw;
            }
           

            //User.Identity.Name == "testKid@aol.com"
 
       
                return View(ButtonList);
          
            
        }

        public ActionResult ErrorPanel()
        {
            var curUser = User.Identity.Name.ToString();
            //System.IO.StreamWriter file = new System.IO.StreamWriter(@"C:\Temp\ControllerLog.txt");
            //file.WriteLine(curUser + " has accessed their panel... " + DateTime.Now.ToString());
            //file.Close();
            //MyMethods.WriteToLog(curUser + " has accessed their panel... ");

            var ButtonList = db.Buttons.ToList();
            bool UserCanUseButton = false;
            //run through each button, remove buttons whos list of users does not match current user
            try
            {
                var ButtonCount = ButtonList.Count();
                for (int i = 0; i <= ButtonCount; i++)
                {
                    var But = ButtonList[0];

                    //Grab a list of users allowed to use this button
                    var userList = But.Users;

                    UserCanUseButton = false;
                    if (userList == null)
                    {

                    }
                    else
                    {
                        string[] aUsers = userList.Split(',');



                        foreach (var ForUser in aUsers)
                        {
                            if (ForUser == curUser)
                            {
                                UserCanUseButton = true;
                            }
                        }
                    }

                    if (curUser == "pjthomas45@gmail.com" | curUser == "adamdthomas@gmail.com")
                    {
                        UserCanUseButton = true;
                    }

                    if (UserCanUseButton == false)
                    {
                        ButtonList.Remove(But);
                    }


                }
            }
            catch (Exception e)
            {
                MyMethods.WriteToLog(e.ToString());
                //throw;
            }


            //User.Identity.Name == "testKid@aol.com"
            return View(ButtonList);
        }

        // GET: Buttons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Button button = db.Buttons.Find(id);
            if (button == null)
            {
                return HttpNotFound();
            }
            return View(button);
        }

        // GET: Buttons/Create
        public ActionResult Create()
        {

            ViewBag.responselist = MyMethods.ResponseTypes();
            return View();
        }

        // POST: Buttons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ButtonID,Label,Style,URI,Response,TimeOut,Users")] Button button)
        {

            //ViewBag.responselist = MyMethods.ResponseTypes(value["responseID"]);
    



            if (ModelState.IsValid)
            {

                db.Buttons.Add(button);
                db.SaveChanges();


                return RedirectToAction("Index");
            }

            return View(button);
        }

        // GET: Buttons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Button button = db.Buttons.Find(id);
            if (button == null)
            {
                return HttpNotFound();
            }
            return View(button);
        }

        // POST: Buttons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ButtonID,Label,Style,URI,Response,TimeOut,Users")] Button button)
        {
            if (ModelState.IsValid)
            {
                db.Entry(button).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(button);
        }

        // GET: Buttons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Button button = db.Buttons.Find(id);
            if (button == null)
            {
                return HttpNotFound();
            }
            return View(button);
        }

        // POST: Buttons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Button button = db.Buttons.Find(id);
            db.Buttons.Remove(button);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HalloweenController v0.0.1/Views/Buttons/Create.cshtml
@model HalloweenController_v0._0._1.Models.Button

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@if (Request.IsAuthenticated)
{
    if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com" | User.Identity.Name == "mspeterson@gmail.com")
    {

        using (Html.BeginForm()) 
        {
            @Html.AntiForgeryToken();
    
            <div class="form-horizontal">
                <h4>Button</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Label, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Style, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Style, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.URI, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.URI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.URI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Response, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Response, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Response, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TimeOut, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TimeOut, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TimeOut, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Users, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Users, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div >
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
}
else
{
    <br />
    <br />
<div class="jumbotron">
    <h1>Get Out!</h1>
    <p class="lead">You are not authorized to view this page.</p>
</div>
}

HalloweenController v0.0.1/Views/Buttons/Delete.cshtml
@model HalloweenController_v0._0._1.Models.Button
@if (Request.IsAuthenticated)
{
    if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com" | User.Identity.Name == "mspeterson@gmail.com")
    {
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Button</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Label)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Label)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Style)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Style)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.URI)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.URI)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Response)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Response)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TimeOut)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TimeOut)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Users)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Users)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>

    }
}

else
{
    <br />
    <br />
    <div class="jumbotron">
        <h1>Get Out!</h1>
        <p class="lead">You are not authorized to view this page.</p>
    </div>
}

HalloweenController v0.0.1/Views/Buttons/Details.cshtml
@model HalloweenController_v0._0._1.Models.Button

<div>
    <h4>Button</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Label)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Label)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Response)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Response)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ButtonID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HalloweenController v0.0.1/Views/Buttons/Edit.cshtml
@model HalloweenController_v0._0._1.Models.Button

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@if (Request.IsAuthenticated)
    {
        if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com" | User.Identity.Name == "mspeterson@gmail.com")
        {

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
    
            <div class="form-horizontal">
                <h4>Button</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ButtonID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Label, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Style, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Style, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.URI, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.URI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.URI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Response, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Response, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Response, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TimeOut, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TimeOut, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TimeOut, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Users, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Users, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        }
    }
else
{
    <br />
    <br />
    <div class="jumbotron">
        <h1>Get Out!</h1>
        <p class="lead">You are not authorized to view this page.</p>
    </div>
}

HalloweenController v0.0.1/Views/Buttons/ErrorPanel.cshtml
@model IEnumerable<HalloweenController_v0._0._1.Models.Button>

<br />

<div class="maingroup">
    <div class="panel panel-default">
        <div class="panel-heading">- Halloween Prop  Control Panel -</div>
        <div class="panel-body" id="buttonholder">



            @foreach (var item in Model)
            {
                <div id="@item.Label" class="icon">
                   
                    <input type="button" value="@item.Label" class="btn btn-@item.Style btn-lg" onclick="location.href='@Url.Action("TestClick", "Buttons", new { URI = item.URI })';Respond('@item.Response', '@item.TimeOut', '@item.Label')" />
                   <!-- <input type="button" value="@item.Label" class="btn btn-@item.Style btn-lg" onclick="Respond('@item.Response', '@item.TimeOut');location.href='@Url.Action("TestClick", "Buttons", new { URI = item.URI })'" />
                 <input type="button" value="@item.Label" class="btn btn-@item.Style btn-lg" onclick="Respond('@item.Response', '@item.TimeOut', '@item.Label')" /> -->

                </div>
            }
        </div>
    </div>
</div>

<br />
<br />


 <span class="label label-danger">Your request did not make it to the controller. You are terrible and should feel bad.</span>

HalloweenController v0.0.1/Views/Buttons/Index.cshtml
@model IEnumerable<HalloweenController_v0._0._1.Models.Button>

@if (Request.IsAuthenticated)
{
    if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com" | User.Identity.Name == "mspeterson@gmail.com")
    {
        <br />
    <br />

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Label)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Style)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.URI)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Response)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TimeOut)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Users)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(model5Item => item.Label)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Style)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.URI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Response)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeOut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Users)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.ButtonID }) |
                    @Html.ActionLink("Details", "Details", new { id=item.ButtonID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ButtonID })
                </td>
            </tr>
        }

        </table>

   

    <p align="left">
        <input type="button" value="Create New Button" class="btn btn-default btn-lg" onclick="location.href='@Url.Action("Create", "Buttons")'" /> 

        <!--@Html.ActionLink("Create New", "Create")-->
    </p>
    }
    else
    {
        <br />
        <br />
        <div class="jumbotron">
            <h1>Get Out!</h1>
            <p class="lead">You are not authorized to view this page.</p>
        </div>
    }
}
else
{
    <br />
    <br />
<div class="jumbotron">
    <h1>Get Out!</h1>
    <p class="lead">You are not authorized to view this page.</p>
</div>
}

HalloweenController v0.0.1/Views/Buttons/Panel.cshtml
@model IEnumerable<HalloweenController_v0._0._1.Models.Button>


<br />

<div class="maingroup">
    <div class="panel panel-default">
        <div class="panel-heading">- Halloween Prop  Control Panel -</div>
        <div class="panel-body" id="buttonholder">
            @foreach (var item in Model)
            {
                <div id="@item.Label" class="icon">
                    @if (Request.IsAuthenticated)
                    {
                        if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com")
                        {
                            <input type="button" value="@item.Label" class="btn btn-@item.Style btn-lg" onclick="Respond('locknone', '@item.TimeOut', '@item.Label', '@item.URI')" />

                        }
                        else
                        {
                            <input type="button" value="@item.Label" class="btn btn-@item.Style btn-lg" onclick="Respond('@item.Response', '@item.TimeOut', '@item.Label', '@item.URI')" />
                        }

                    }
                </div>
            }
        </div>
    </div>
</div>



<div id="ButtonSuccess">
    <div class="alert alert-success">
        <div id="funnies"></div>
    </div>
</div>
<!--
<div id="ButtonFailure">
    <div class="alert alert-danger">
        Your request did not make it to the controller. You are terrible and should feel bad.
    </div>
</div>
    -->
<script type="text/javascript" src="~/Scripts/REST.js"></script>
<script type="text/javascript">
    setTimeout(function () { hideDivFAST('ButtonSuccess') }, 10);
</script>

@if (Request.IsAuthenticated)
{
    if (User.Identity.Name == "adamdthomas@gmail.com" | User.Identity.Name == "pjthomas45@gmail.com")
    {
    }
    else
    {

        <script type="text/javascript" src="~/Scripts/REST.js"></script>
        <script>
            setTimeout(function () { hideDiv("buttonholder") }, 5);
            setTimeout(function () { showDiv("buttonholder") }, 30000);
            setTimeout(function () { hideDiv("timerholder") }, 33000);
        </script>

        <div id="timerholder">
            <h2>You will have to wait until you can access your buttons.</h2>
            <div class="maingroup">

                <div id="timerid" class="timer">
                    <script type="text/javascript" src="~/Scripts/countdown.js"></script>
                    <script>
                        var myCountdown2 = new Countdown({
                            time: 30, width: 200, height: 80, rangeHi: "second", hideLine: 1, numbers: {
                                font: "Arial",
                                color: "#FFFFFF",
                                bkgd: "#ff8f00",
                                rounded: 0.15,
                                shadow: {
                                    x: 0,
                                    y: 3,
                                    s: 4,
                                    c: "#000000",
                                    a: 0.4
                                }
                            },
                            labels: {
                                font: "Arial",
                                color: "#a8a8a8",
                                weight: "normal"
                            }
                        });
                    </script>
                </div>

            </div>

        </div>
    }


}
else
{
    <div class="jumbotron">
         <p class="lead">You will need to be logged in to view buttons in your Panel.</p>
    </div>
}